name: "Building android apk"
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building android apk
    runs-on: ubuntu-latest
    steps:
      - name: Clone the current repo
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: "gradle"
      
      - name: Giving permission to gradlew
        run: chmod +x gradlew

      - name: Build the apk
        run: ./gradlew assembleRelease --stacktrace
      
      - name: Get build tool version
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
      
      - name: Signing the app
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
      
      - name: Upload the apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

